jns/urls.py
from django.urls import path

from . import views

app_name = 'jns'
urlpatterns = [
    path('home/', views.TemplateView.as_view(template_name = 'jns/main.html'), name='home'),
    path('faulty/', views.fiber, name='faulty'),
    path('search/', views.search, name='search'),
    path('sfp_search/', views.sfp_search, name='sfp_search'),
    path('temp_search/', views.temp_search, name='temp_search'),
    path('temp_list/', views.temp_list, name='temp_list'),
    path('topology/', views.net_topology, name='topology')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('jns-dev/', include('jns.urls')),
    path('admin/', admin.site.urls)
]

jns/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Fiber(models.Model):
    int_name = models.CharField(max_length=200)
    date = models.DateField('date')
    switch = models.CharField(max_length=200)
    rxlevel = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return self.int_name
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=7) <= self.date <= now

class InterfaceCounters(models.Model):
    int_name = models.CharField(max_length=200)
    report_date = models.DateField('report_date')
    switch = models.CharField(max_length=200)
    int_desc = models.CharField(max_length=300)
    
    def __str__(self):
        return self.int_name

class Temperature(models.Model):
    int_name = models.CharField(max_length=200)
    date = models.DateField('date')
    switch = models.CharField(max_length=200)
    temperature = models.DecimalField(max_digits=7, decimal_places=0)

    def __str__(self):
        return self.int_name

jns/forms.py
from django import forms

class SwitchForm(forms.Form):
    switch = forms.CharField(label='Switch:', max_length=20)

jns/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.utils import timezone
import datetime
from . import netbox
from .models import Fiber, InterfaceCounters, Temperature




class AboutView(TemplateView):
    template_name = 'jns/main.html'



def search(request):
    
    if request.method == 'POST':
        search_id = request.POST['textfield']
        switch = (InterfaceCounters.objects
                  .filter(switch__exact = search_id)
                  .using('int_reclaim'))
        context = {
            'switch': switch
        }
        
        return render(request, 'jns/reclaim_results.html', context)
    
    else:
        return render(request, 'jns/reclaim.html')



def fiber(request):
    
    if request.method == 'POST':
        search_id = request.POST['textfield']
        bad_interfaces = (Fiber.objects
                          .filter(date__gte=timezone.now()- datetime.timedelta(days=6))
                          .filter(rxlevel__range=(-30, search_id)))
        context = {
            'bad_interfaces': bad_interfaces
        }
     
        return render(request, 'jns/faulty.html', context)
    
    else:
        return render(request, 'jns/faulty_search.html')



def sfp_search(request):
    
    labels_date = []
    data_rxlevels = []
    interface_name = []

    if request.method == 'POST':
        search_id = request.POST['textfield']
        search_id2 = request.POST['textfield2']
        switch = Fiber.objects.filter(switch__exact = search_id)
        
        queryset = (Fiber.objects
                    .filter(switch__exact = search_id)
                    .filter(int_name__exact = search_id2)
                    .order_by('date'))
        
        for switch_name in queryset:
            labels_date.append(switch_name.date)
            data_rxlevels.append(switch_name.rxlevel)
            interface_name.append(switch_name.int_name)
        
        context = {
            'switch' : switch,
            'labels_switch': search_id,
            'labels_date': labels_date,
            'data_rxlevels': data_rxlevels,
            'interface_name': interface_name
        }
        
        return render(request, 'jns/sfp_history_results.html', context)
    
    else:
        return render(request, 'jns/sfp_history.html')



def temp_search(request):
    
    labels_date = []
    data_temp = []
    interface_name = []
    
    if request.method == 'POST':
        search_id = request.POST['textfield']
        search_id2 = request.POST['textfield2']
        search_id3 = request.POST['textfield3']
        switch = Temperature.objects.filter(switch__exact = search_id).using('temperature')
        queryset = (Temperature.objects
                    .filter(switch__exact = search_id)
                    .filter(date__range=[search_id2, search_id3])
                    .order_by('date')
                    .using('temperature'))

        for switch_name in queryset:
            labels_date.append(switch_name.date)
            data_temp.append(switch_name.temperature)
            interface_name.append(switch_name.int_name)
        
        context = {
            'switch': switch,
            'labels_switch': search_id,
            'labels_date': labels_date,
            'data_temp': data_temp,
            'interface_name': interface_name
        }
        
        return render(request, 'jns/temp_history_results.html', context)
    
    else:
        return render(request, 'jns/temp_history.html')



def temp_list(request):
    
    labels_date = []
    data_temp = []
    
    if request.method == 'POST':

        search_id = request.POST['temp_history_submit']

        switch = Temperature.objects.filter(switch__exact = search_id).using('temperature')
        
        queryset = (Temperature.objects
                    .filter(switch__exact = search_id)
                    .order_by('date')
                    .using('temperature'))

        for switch_name in queryset:
            labels_date.append(switch_name.date)
            data_temp.append(switch_name.temperature)
        
        context = {
            'switch': switch,
            'labels_switch': search_id,
            'labels_date': labels_date,
            'data_temp': data_temp,
        }
        
        return render(request, 'jns/temp_history_results.html', context)
    
    else:
        queryset = (Temperature.objects
                    .filter(date__gte=timezone.now()- datetime.timedelta(days=0))
                    .order_by('-temperature')
                    .using('temperature'))
        
        if len(queryset) <= 0:
            
            queryset = (Temperature.objects
                    .filter(date__gte=timezone.now()- datetime.timedelta(days=1))
                    .order_by('-temperature')
                    .using('temperature'))
            
            if len(queryset) <= 0:
            
                queryset = (Temperature.objects
                        .filter(date__gte=timezone.now()- datetime.timedelta(days=3))
                        .order_by('-temperature')
                        .using('temperature'))
    
        context = {
            'switch' : queryset
        }
        
        return render(request, 'jns/temp_list.html', context)



def net_topology(request):

    if request.method == 'POST':
        
        search_id = request.POST['textfield']
        
        api_result, api_data, device_id = netbox.netbox_req(search_id)

        if api_result:
            
            context = {
                'labels_switch': search_id,
                'device_id': device_id,
                'api_data' : api_data,
            }
            
            return render(request, 'jns/netbox_results.html', context)

        else:
            
            context = {
                'error' : "No connections found, please try again or enter a different device."
            }
            
            return render(request, 'jns/netbox.html', context)   
    
    else:
        return render(request, 'jns/netbox.html')

jns/templates/jns/faulty.html
{% load static %}
{% if bad_interfaces %}
<!DOCTYPE html>
<html>
    <head>
        <title>Bad Interfaces</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <div class="header">
            <p>Bad Interfaces</p>
            <hr/>
        </div>
        <div class="maintext">
            <p>This displays all interfaces that are below the chosen receive (rx) threshold.</p>
            </br>
        </div>
        <div align="center">
            <table>
                <tr >
                    <style>th {padding: 10px;}</style>
                    <th align="center"> Switch </th>
                    <th align="center">  Int_name  </th>
                    <th align="center">  Rxlevel </th>
                    <th align="center"> Date </th>
                </tr>
                {% for interface in bad_interfaces %}
                <tr valign="Top">
                    <td valign="right">{{ interface.switch }}</td>
                    <td valign="right">{{ interface.int_name }}</td>
                    <td valign="right">{{ interface.rxlevel }}</td>
                    <td valign="right">{{ interface.date }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div align="center">
                <p><a class="link" href=#top>back to top</a></p>
        </div>
        <div align="center">
            <form action="{% url 'jns:faulty' %}" >
                <button class="button-link" type="submit">Back to Bad Interfaces</button>
            </form>
        </div>
        <div align="center">
            <form action="{% url 'jns:home' %}" >
                <button class="button-link" type="submit">Back to Home Screen</button>
            </form>
        </div>
    </body>
{% else %}
<!DOCTYPE html>
<html>
    <head>
        <title>Bad Interfaces Error</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <div class="header">
            <p>No interfaces are available. Please select a lower threshold value.</p>
        </div>
        <div align="center">
            <form action="{% url 'jns:faulty' %}" >
                <button class="button-link" type="submit">Back to Bad Interfaces</button>
            </form>
        </div>
        <div align="center">
            <form action="{% url 'jns:home' %}" >
                <button class="button-link" type="submit">Back to Home Screen</button>
            </form>
        </div>
</body>
{% endif %}

jns/templates/jns/faulty_search.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Bad Interfaces</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
    <div>
        <p class="header">Bad Interfaces Home</p>
        <hr/>
    </div>
    <div class="maintext">
        <p>Enter the rx level threshold you wish to search for (between 0 and -29).</p>
    </div>
    <div class="center padding" >
        <form method="POST">
            {% csrf_token %}
            <div align="center" class="subtext">
                RX Level:
            </div>
            <div>
                <input class="textinput" type="number" minlength="1" name="textfield" required>
            </div>
            </br>
            <div align="center">
                <button class="buttonsubmit" type="submit">Submit</button>
            </div>
        </form>
    </div>
    <div align="center">
        <form action="{% url 'jns:home' %}" >
            <button class="button-link" type="submit">Back to Home Screen</button>
        </form>
    </div>
</body>

jns/templates/jns/main.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>JNS Home</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <div>
            <p class="header">Jim's Networking Shop<br/> (JNS)</p>
            <hr/>
        </div>
        <div class="maintext">
            <p>This is the main page for tools created by James Maschal</p>
        </div>
        <div class="padding"></div>
        <div align="center">
            <form action="{% url 'jns:faulty' %}">
            <button class="button-link" type="submit">Bad Fiber Interfaces</button>
            </form>
        </div>
        <div align="center">
            <form action="{% url 'jns:search' %}">
            <button class="button-link" type="submit">Port Reclaim</button>
            </form>
        </div>
        <div align="center">
            <form action="{% url 'jns:sfp_search' %}">
            <button class="button-link" type="submit">SFP History</button>
            </form>
        </div>
        <div align="center">
            <form action="{% url 'jns:temp_search' %}">
            <button class="button-link" type="submit">Switch Temperature History</button>
            </form>
        </div>
        <div align="center">
            <form action="{% url 'jns:topology' %}">
            <button class="button-link" type="submit">Network Topology</button>
            </form>
        </div>
    </body>
    </html>

jns/templates/jns/netbox.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Network Topology</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
    <div>
        <p class="header">Network Topology</p>
        <hr/>
        <div class="maintext">
            <p>Enter the CORE/DIST router you wish to see the topology of.</p>
            <p>Please ensure the switch name is spelled correctly.</p></br>
            <p>Nodes can be selected to open the NetBox trace-path for that connection.</p>
        </div>
    </div>
    <div class="center padding">
        <form method="POST">
        {% csrf_token %}
            <div class="subtext">
                Router: <input class="textinput" type="text" name="textfield" required>
            </div>
            </br>
            <div align="center">
                {% if error %}
                <p class="subtext">{{ error }}</p>
                {% endif %}
                <button class="buttonsubmit" type="submit">Submit</button>
            </div>
        </form>
    </div>
    <div align="center">
        <form action="{% url 'jns:home' %}" >
            <button class="button-link" type="submit">Back to Home Screen</button>
        </form>
    </div>
    </body>

jns/templates/jns/netbox_results.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  <head>
    <title>{{ labels_switch }}</title>
    <script src=" https://cdn.jsdelivr.net/npm/cytoscape@3.24.0/dist/cytoscape.min.js "></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  </head>
  <body>
    <div id="cy"></div>
    <div class="button-container">
      <form action="{% url 'jns:topology' %}" >
        <button type="submit">Back to Network Topology</button>
      </form>
      <form action="{% url 'jns:home' %}" >
        <button type="submit">Back to Home Screen</button>
      </form>
    </div>
    <script>
        var cy = cytoscape({
          container: document.getElementById('cy'),
          
          elements:[
          {% for data in api_data %}
          { data: { id: "{{ data.id_val }}", label: "{{ data.display_val }}\n\n{{ data.peer_val }}"} },
          { data: { id: "{{ data.id_val }}-{{ data.peer_val }}", source: "{{ data.id_val }}", target: "{{ device_id }}" } },
          {% endfor %}
          
          { data: {id: "{{ device_id }}", label: "{{ labels_switch }}" } },
          ],
          
          style: [
          {
            selector: 'node',
            style: {
              'background-color': '#3775a8',
              'label': 'data(label)',
              'text-background-opacity': 1,
              'text-background-color': '#3c444d',
              'text-background-shape': 'roundrectangle',
              'text-background-padding': '10px',
              'color': '#ffffff',
              'font-size': '1.25em',
              'text-wrap': 'wrap',
            }
          },
          {
            selector: 'edge',
            style: {
              'width': 1,
              'line-color': '#4b99da',
              'curve-style': 'bezier'
            }
          }],
        });
        var layout = cy.layout({
          name: 'grid',
          avoidOverlap: true,
          nodeDimensionsIncludeLabels: true,
          });
        layout.run();
        cy.on('click', 'node', function(){
          if (this.id() === "{{ device_id }}") {
            try { // your browser may block popups
              window.open("https://YOUR-SERVER-HERE/dcim/devices/" + this.data('id'));
            } catch(e){ // fall back on url change
              window.location.href = "https://YOUR-SERVER-HERE/dcim/devices/" + this.data('id');
            }
          } 
          else {
            try { // your browser may block popups
              window.open("https://YOUR-SERVER-HERE/dcim/interfaces/" + this.data('id') + "/trace/");
            } catch(e){ // fall back on url change
              window.location.href = "https://YOUR-SERVER-HERE/dcim/interfaces/" + this.data('id') + "/trace/";
            }
          }
        });
        
    </script>
  </body>
</html>

jns/templates/jns/reclaim.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Bad Interfaces</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <div>
            <p class="header">Port Reclaim</p>
            <hr/>
        </div>
        <div>
            <p class="maintext">Enter the switch you wish to perform port reclaim on.</p>
            <br/>
            <p class="maintext">Please ensure the switch name is spelled correctly, and in all caps.</p>
        </div>
        <div class="center padding" >
            <form style="text-align: center;"  method="POST">
                {% csrf_token %}
                <div align="center" class="subtext">
                    Switch:
                </div>
                <div>
                    <input class="textinput" type="text" minlength="1" name="textfield" required>
                </div>
                    </br>
                <div align="center">
                    <button class="buttonsubmit" type="submit">Submit</button>
                </div>
            </form>
        </div>
        <div align="center">
            <form action="{% url 'jns:home' %}" >
                <button class="button-link" type="submit">Back to Home Screen</button>
            </form>
        </div>
    </body>

jns/templates/jns/reclaim_results.html
{% load static %}
{% if switch %}
<!DOCTYPE html>
<html>
    <head>
        <title>Bad Interfaces</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <div>
            <p class="header">Reclaim Results</p>
            <hr/>
        </div>
        <div align="center">
            <table >
                <tr>
                    <th align="center">Switch</th>
                    <th align="center">Interface</th>
                    <th align="center">Description</th>
                    <th align="center">Date</th>
                </tr>
            {% for interface in switch %}
                <tr valign="Top">
                    <td valign="right">{{ interface.switch }}</td>
                    <td valign="right">{{ interface.int_name }}</td>
                    <td valign="right">{{ interface.int_desc }}</td>
                    <td valign="right">{{ interface.report_date }}</td>
                </tr>
            {% endfor %}
            </table>
        </div>
        <div align="center">
            <p><a class="link" href=#top>back to top</a></p>
        </div>
        <div align="center">
            <form action="{% url 'jns:search' %}" >
                <button class="button-link" type="submit">Back to Port Reclaim</button>
            </form>
        </div>
        <div align="center">
            <form action="{% url 'jns:home' %}" >
                <button class="button-link" type="submit">Back to Home Screen</button>
            </form>
        </div>
    </body>
{% else %}
<!DOCTYPE html>
<html>
    <head>
        <title>Port Reclaim Error</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <div class="header">
            <p>No interfaces are available. This switch is unavailable for reclaim or was spelled incorrectly.</p>
            <br/>
            <p>Please ensure the switch name is spelled correctly, and in all caps.</p>
        </div>
        <div align="center">
            <form action="{% url 'jns:search' %}" >
                <button class="button-link" type="submit">Back to Port Reclaim</button>
            </form>
        </div>
        <div align="center">
            <form action="{% url 'jns:home' %}" >
                <button class="button-link" type="submit">Back to Home Screen</button>
            </form>
        </div>
</body>
{% endif %}

jns/templates/jns/sfp_history_results.html
{% load static %}
{% if switch %}
{% if interface_name %}
<!DOCTYPE html>
<html>
<head>
	<title>{{ labels_switch }}</title>
	<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
	<div align="middle" id="container" style="max-width: 70%; margin:auto; padding-bottom: 30px;">
		<canvas id="sfp_search"></canvas>
	</div>
	<script>
		const ctx = document.getElementById('sfp_search').getContext('2d');
		const sfp_search = new Chart(ctx, {
			type: 'line',
			data: {
				labels: [{% for item in labels_date %}"{{ item }}",{% endfor %}],
				  datasets: [{
					  label: '{{ labels_switch }}',
					  data: [{% for item in data_rxlevels %}"{{ item }}",{% endfor %}],
					  borderColor: '#4b99da',
				  }]
			},
			options: {
				plugins:{
					legend:{
						display: true,
						position: 'bottom',
						labels: {
							color: '#ffffff'
						}
					},
					title: {
						display: true,
						text: 'SFP Optical RX History',
						color: '#ffffff',
						font: {
							size: 18
						},
						padding: {
							top: 30,
							bottom: 30
						}
					}
				},
				repsonsive: true,
				elements: {
					point: {backgroundColor:'#ffffff'}
				},
				layout: {
					padding: {
						top: 40,
					}
				},
				scales: {
					y: {
						grid: { color: '#bbbbbb'},
						ticks: { color: '#ffffff', beginAtZero: true}
					},
					x: {
						grid: { color: '#bbbbbb'},
						ticks: { color: '#ffffff', beginAtZero: true}
					}
				}
			}
		});
	</script>
	<div align="center">
		<form action="{% url 'jns:sfp_search' %}" >
			<button class="button-link" type="submit">Back to SFP History</button>
		</form>
	</div>
    <div align="center">
        <form action="{% url 'jns:home' %}" >
            <button class="button-link" type="submit">Back to Home Screen</button>
        </form>
    </div>
</body>
</html>
{% else %}
<!DOCTYPE html>
<html>
<head>
	<title>Chart Error</title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
	<div>
    	<h1 class="header">No information available.<br/> Either that switch/interface is unavailable or the hostname was entered incorrectly.
		<br/><br/>Please ensure the switch name is spelled correctly.</h1>
	</div>
	<div align="center">
		<form action="{% url 'jns:sfp_search' %}" >
			<button class="button-link" type="submit">Back to SFP History</button>
		</form>
	</div>
    <div align="center">
        <form action="{% url 'jns:home' %}" >
            <button class="button-link" type="submit">Back to Home Screen</button>
        </form>
    </div>
</body>
{% endif %}
{% endif %}

jns/templates/jns/temp_history.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Temperature History</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
    <div>
        <p class="header">Switch Inlet Temperature History</p>
        <hr/>
        <div class="maintext">
            <p>Enter the switch you wish to see the temperature history of.</p>
            <p>Then, enter the number of days back you wish to see.</p>
            <p>Please ensure the switch name is spelled correctly.</p>
        </div>
    </div>
    <div align="center" style="padding: 20px">
        <form action="{% url 'jns:temp_list' %}" >
            <button class="button-link" type="submit">Full Device List</button>
        </form>
    </div>
    <div class="center padding">
        <form method="POST">
        {% csrf_token %}
            <div class="subtext">
                Swtich:
            </div>
            <div>
                <input class="textinput" type="text" name="textfield" required>
            </div>
            </br>
            <div class="subtext">
                Start Date:
            </div>
            <div>
                <input class="textinput" type="date" name="textfield2" required>
            </div>
            </br>
            <div class="subtext">
                End Date:
            </div>
            <div>
                <input class="textinput" type="date" name="textfield3" required>
            </div>
            </br>
            <div align="center">
                <button class="buttonsubmit" type="submit">Submit</button>
            </div>
        </form>
    </div>
    <div align="center">
        <form action="{% url 'jns:home' %}" >
            <button class="button-link" type="submit">Back to Home Screen</button>
        </form>
    </div>
    </body>

jns/templates/jns/temp_history_results.html
{% load static %}
{% if switch %}
<!DOCTYPE html>
<html>
<head>
	<title>{{ labels_switch }}</title>
	<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
	<div align="middle" id="container" style="max-width: 70%; margin:auto; padding-bottom: 30px;">
		<canvas id="temp_search"></canvas>
	</div>
	<script>
		const ctx = document.getElementById('temp_search').getContext('2d');
		const temp_search = new Chart(ctx, {
			type: 'line',
			data: {
				labels: [{% for item in labels_date %}"{{ item }}",{% endfor %}],
				  datasets: [{
					  label: '{{ labels_switch }}',
					  data: [{% for item in data_temp %}"{{ item }}",{% endfor %}],
					  borderColor: '#4b99da',
				  }]
			},
			options: {
				plugins:{
					legend:{
						display: true,
						position: 'bottom',
						labels: {
							color: '#ffffff'
						}
					},
					title: {
						display: true,
						text: 'Switch Temperature History',
						color: '#ffffff',
						font: {
							size: 18
						},
						padding: {
							top: 30,
							bottom: 30
						}
					}
				},
				repsonsive: true,
				elements: {
					point: {backgroundColor:'#ffffff'}
				},
				layout: {
					padding: {
						top: 40,
					}
				},
				scales: {
					y: {
						grid: { color: '#bbbbbb'},
						ticks: { color: '#ffffff', beginAtZero: true}
					},
					x: {
						grid: { color: '#bbbbbb'},
						ticks: { color: '#ffffff', beginAtZero: true}
					}
				}
			}
		});
	</script>
	<div align="center">
		<form action="{% url 'jns:temp_search' %}" >
			<button class="button-link" type="submit">Back to Temperature History</button>
		</form>
	</div>
    <div align="center">
        <form action="{% url 'jns:home' %}" >
            <button class="button-link" type="submit">Back to Home Screen</button>
        </form>
    </div>
</body>
</html>
{% else %}
<!DOCTYPE html>
<html>
<head>
	<title>Chart Error</title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
	<div>
    	<h1 class="header">No information available.<br/> Either that switch is unavailable or the hostname was entered incorrectly.
		<br/><br/>Please ensure the switch name is spelled correctly.</h1>
	</div>
	<div align="center">
		<form action="{% url 'jns:temp_search' %}" >
			<button class="button-link" type="submit">Back to Temperature History</button>
		</form>
	</div>
    <div align="center">
        <form action="{% url 'jns:home' %}" >
            <button class="button-link" type="submit">Back to Home Screen</button>
        </form>
    </div>
</body>
{% endif %}

jns/templates/jns/temp_list.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Switch Temperature List</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <style>
            .table-button {
                background-color: #2e343a;
                color: #4b99da;
                border: 0px;
                font-size: 1em;
            }

            .table-button:hover {
                background-color: #515c68;
                cursor: pointer;
            }
        </style>
    </head>
    <body>
        <div>
            <p class="header">Full Device List</p>
            <hr/>
        </div>
        <div align="center">
            <table >
                <tr>
                    <th align="center">Switch</th>
                    <th align="center">Temperature</th>
                    <th align="center">Date of Last Record</th>
                </tr>
            {% for interface in switch %}
                <tr valign="Top">
                    <td valign="right">
                        <form method="post">
                            {% csrf_token %}
                            <input type="submit" name="temp_history_submit" value="{{ interface.switch }}" class="table-button">
                        </form></td>
                    <td valign="right">{{ interface.temperature }}</td>
                    <td valign="right">{{ interface.date }}</td>
                </tr>
            {% endfor %}
            </table>
        </div>
        <div align="center">
            <p><a class="link" href=#top>back to top</a></p>
        </div>
        <div align="center">
            <form action="{% url 'jns:temp_search' %}" >
                <button class="button-link" type="submit">Temperature History</button>
            </form>
        </div>
        <div align="center">
            <form action="{% url 'jns:home' %}" >
                <button class="button-link" type="submit">Back to Home Screen</button>
            </form>
        </div>
    </body>